version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 15
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: simplecov
    versions:
    - "> 0.17.1, < 1"
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.9.0
