require:
  - 'rubocop-rspec'

AllCops:
  TargetRubyVersion: 2.3

  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/http_wrapper_spec.rb'

Metrics/MethodLength:
  Max: 15

Bundler/OrderedGems:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
