plugins:
  - 'rubocop-rspec'
  - 'rubocop-performance'

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 15

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false
