language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode

gemfile: Gemfile.ci

notifications:
  recipients: leonid@svyatov.ru
  on_failure: change

matrix:
  allow_failures:
    - rvm:
      - ruby-head
